config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :quickbooks, only: [:show, :edit, :update] do
      resource :products_syncs, only: :create, module: :quickbooks
      collection do
        get :authenticate
        get :oauth_callback
      end
    end
  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do

  after_update do
    if self.state == 'complete'
      create_or_update_order
    end
  end

  private


  def create_or_update_order
   SpreeQuickbooks::Sync::Order.new(self).perform
  end

end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do

  before_save do
    if changes[:sku] && changes[:sku].any?
      update_variant
    end
  end

  private

  def update_variant
    SpreeQuickbooks::Sync::Variant.new(changes[:sku]).perform
  end

end

app/controllers/spree/admin/quickbooks/products_syncs_controller.rb
module Spree
  module Admin
    module Quickbooks
      class ProductsSyncsController < Spree::Admin::BaseController

        def create
          SpreeQuickbooks::Sync::Products.new.perform
          redirect_to admin_quickbooks_path
        end


      end
    end
  end
end

app/controllers/spree/admin/quickbooks_controller.rb
module Spree
  module Admin
    class QuickbooksController < BaseController

      def show

      end

      def authenticate
        callback = oauth_callback_admin_quickbooks_url
        token = consumer.get_request_token(:oauth_callback => callback)
        session[:qb_request_token] = Marshal.dump(token)
        redirect_to("https://appcenter.intuit.com/Connect/Begin?oauth_token=#{token.token}") and return
      end

      def oauth_callback
        at = Marshal.load(session[:qb_request_token]).get_access_token(:oauth_verifier => params[:oauth_verifier])
        SpreeQuickbooks::Config[:quickbooks_realm] = params['realmId']
        SpreeQuickbooks::Config[:quickbooks_access_token] = at.token
        SpreeQuickbooks::Config[:quickbooks_access_secret] = at.secret
        redirect_to admin_quickbooks_url, notice: 'Your QuickBooks account has been successfully linked.'
      end

      private

      def consumer
        OAuth::Consumer.new(SpreeQuickbooks::Config[:quickbooks_key], SpreeQuickbooks::Config[:quickbooks_secret], {
                                                                        :site => 'https://oauth.intuit.com',
                                                                        :request_token_path => '/oauth/v1/get_request_token',
                                                                        :authorize_url => 'https://appcenter.intuit.com/Connect/Begin',
                                                                        :access_token_path => '/oauth/v1/get_access_token'
                                                                    })
      end
    end
  end
end

app/helpers/spree/quickbooks_helper.rb
module Spree
  module QuickbooksHelper
    def quickbooks_integrated?
      SpreeQuickbooks::Config[:quickbooks_realm]
    end
  end
end

app/views/spree/admin/quickbooks/show.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:quickbooks_settings) %>
    <% unless false && SpreeQuickbooks::Config[:quickbooks_realm] %>
        <ipp:connectToIntuit></ipp:connectToIntuit>
    <% end %>
<% end %>

<% content_for :page_actions do %>
    <li id="new_product_link">
      <%= button_to Spree.t(:sync_products), admin_quickbooks_products_syncs_path, method: :post %>
    </li>
<% end %>
<script type="text/javascript" src="https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js"></script>

<script>
    intuit.ipp.anywhere.setup({menuProxy: '/path/to/blue-dot', grantUrl: '<%= authenticate_admin_quickbooks_url %>'});
</script>


<div class="twelve columns">
  <fieldset class="alpha twelve columns">
    <legend>API Access</legend>
    <% [:quickbooks_access_token, :quickbooks_access_secret, :quickbooks_realm].each do |key| %>
        <div class="field">
          <div><%= Spree.t(key) %>: <%= SpreeQuickbooks::Config[key] %> </div>
        </div>
    <% end %>
  </fieldset>
</div>